stages:
  - pre_release # a single stage allows test to run even if flake8 fails and makes it possible to get all the errors at once
  - release

flake8:
  extends:
    - .except_nightly_test
  tags:
    - docker
  image: python:3
  stage: pre_release
  script:
    - pip install black flake8 flake8-black pep8-naming flake8-bugbear --constraint requirements-dev.txt
    - flake8 -v mixer tests extra

mypy:
  extends:
    - .except_nightly_test
  tags:
    - docker
  image: python:3
  stage: pre_release
  script:
    - pip install mypy --constraint requirements-dev.txt
    - mypy mixer
  allow_failure: true

doc:
  stage: pre_release
  extends:
    - .except_nightly_test
  tags:
    - docker
  image: python:3
  when: manual
  script:
    - pip install sphinx sphinx-rtd-theme
    - sphinx-build -b html docs docs/_build/html
    - rm -rf docs/_build/doctree
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}_html"
    paths:
      - docs/_build
    expire_in: 1 week

zip:
  extends:
    - .except_nightly_test
  tags:
    - docker
  image: alpine
  stage: pre_release
  script:
    - cp CHANGELOG.md README.md LICENSE mixer/
    - rm -rf mixer/blender_data/tests/
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}"
    paths:
      - mixer
    expire_in: 1 week

# Note: you cannot extend this job with another only: variables job
# If you need that, you should rewrite and combine the rules
.only_version_tag:
  only:
    refs:
      # see inject_version.py
      - /^v([0-9]+)\.([0-9]+)\.([0-9]+)(\-[0-9A-Za-z-]+)?(\+[0-9A-Za-z-]+)?$/

.except_nightly_test:
  except:
    variables:
      - $NIGHTLY_TEST == "true"

.only_nightly_test:
  only:
    variables:
      - $NIGHTLY_TEST == "true"

release:
  extends:
    - .only_version_tag
    - .except_nightly_test
  dependencies:
    - zip
  tags:
    - docker
  image: python:3
  stage: release
  script:
    - pip install requests
    - rm -rf mixer/blender_data/tests/
    - python -m zipfile -c mixer-${CI_COMMIT_REF_NAME}.zip mixer/
    - python -m gitlab.release mixer-${CI_COMMIT_REF_NAME}.zip
  artifacts:
    paths:
      - mixer-${CI_COMMIT_REF_NAME}.zip

####################################################################################


.test_base:
  stage: pre_release
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[skip-tests\]/
  tags:
    - blender
  variables:
    MIXER_BASH_EXE: C:\Program Files\Git\bin\bash.exe
    VRTIST_PORT: 25600 # In case a server is already running on our default port on the test computer
    MIXER_TEST_OUTPUT: logs\tests
  timeout: 2h
  script:
    - gitlab\run_unittest.bat
  cache:
    paths:
      - gitlab/blender/cache
  artifacts:
    paths:
      - logs\tests\*.xml
    reports:
      junit:
        - logs\tests\*.xml

.test_version_dev:
  variables:
    MIXER_BLENDER_ZIP_BASENAME: blender-2.92.0-windows64
    MIXER_BLENDER_VERSION_BASE: "2.92"
    MIXER_BLENDER_DOWNLOAD: "release"

test_dev:
  extends:
    - .test_base
    - .test_version_dev
    - .except_nightly_test

.test_version_2.83.13:
  extends:
    - .test_base
  variables:
    MIXER_BLENDER_VERSION_BASE: "2.83"
    MIXER_BLENDER_ZIP_BASENAME: blender-2.83.13-windows64
    MIXER_BLENDER_DOWNLOAD: "release"

test_2.83.13:
  extends:
    - .test_version_2.83.13
    - .only_nightly_test

test_2.83.13_manual:
  extends:
    - .test_version_2.83.13
    - .except_nightly_test
  when: manual

.test_version_2.93.beta:
  extends:
    - .test_base
  variables:
    MIXER_BLENDER_VERSION_BASE: "2.93"
    # from https://builder.blender.org/download/
    MIXER_BLENDER_ZIP_BASENAME: blender-2.93.${blender_2_93_beta}-windows64
    MIXER_BLENDER_DOWNLOAD: "builder"

test_2.93.beta:
  extends:
    - .test_version_2.93.beta
    - .only_nightly_test

test_2.93.beta_manual:
  extends:
    - .test_version_2.93.beta
    - .except_nightly_test
  when: manual

.test_version_3.0.alpha:
  extends:
    - .test_base
  variables:
    MIXER_BLENDER_VERSION_BASE: "3.0"
    # from https://builder.blender.org/download/
    MIXER_BLENDER_ZIP_BASENAME: blender-3.0.${blender_3_0_alpha}-windows64
    MIXER_BLENDER_DOWNLOAD: "builder"

test_3.0.alpha:
  extends:
    - .test_version_3.0.alpha
    - .only_nightly_test

test_3.0.alpha_manual:
  extends:
    - .test_version_3.0.alpha
    - .except_nightly_test
  when: manual

